package Execptionalhandling;

public class Execption1 {
public static void main(String[] args) {
	try {
		int a=5;
		int b=0;
		int c=a/b;
		System.out.println(c);
	}catch(ArithmeticException e) {
		System.out.println(e.getMessage() +" occured ,please check");
	}catch(IndexOutOfBoundsException e) {
		System.out.println("check the array");
	}finally {
		System.out.println("sorry for the inconvineince");
	}
	System.out.println("very imp code ");
	System.out.println("need to run");
}
}
